<?php

namespace AppBundle\Repository;

/**
 * bientypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bientypeRepository extends \Doctrine\ORM\EntityRepository
{
}
