<?php

namespace AppBundle\Repository;

/**
 * DemandeImmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeImmoRepository extends \Doctrine\ORM\EntityRepository
{
}
